DATABASE_HOST="127.0.0.1"
DATABASE_PORT=3306
DATABASE_USER="root"
DATABASE_PASS="root"
DATABASE_NAME="db"
DATABASE_PREFIX=""

SECRET_KEY="ASuperSecretKeyThatMustBeLongAndRandomAndSecretDoNotUseThisMessage"

SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/auth.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
